{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
  annotations:
    {{- include "gateway-api.annotations" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  {{- range .Values.gateway.listeners }}
  {{- if or (not (hasKey . "enabled")) .enabled }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      {{- if .tls }}
      tls:
        mode: {{ .tls.mode }}
        {{- if .tls.certificateRefs }}
        certificateRefs:
        {{- range .tls.certificateRefs }}
          - name: {{ .name }}
            {{- if .kind }}
            kind: {{ .kind }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- if .tls.options }}
        options:
          {{- toYaml .tls.options | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .allowedRoutes }}
      allowedRoutes:
        namespaces:
          from: {{ .allowedRoutes.namespaces.from }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
