{{- if .Values.referenceGrants.enabled }}
{{- range .Values.referenceGrants.grants }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "gateway-api.labels" $ | nindent 4 }}
  annotations:
    {{- include "gateway-api.annotations" $ | nindent 4 }}
spec:
  from:
  {{- range .from }}
    - group: {{ .group }}
      kind: {{ .kind }}
      namespace: {{ .namespace }}
  {{- end }}
  to:
  {{- range .to }}
    - group: {{ .group }}
      kind: {{ .kind }}
      {{- if .name }}
      name: {{ .name }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
