// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn1HhAGfV3EVX4rwvid6-FDKNafRa3xNU',
    appId: '1:485836775960:web:6f928a17c2b827b138d96d',
    messagingSenderId: '485836775960',
    projectId: 'altrupets-dev',
    authDomain: 'altrupets-dev.firebaseapp.com',
    storageBucket: 'altrupets-dev.firebasestorage.app',
    measurementId: 'G-57YSYL4YK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1TOiIrowifFMePStlmSjav-7G-meuKBY',
    appId: '1:485836775960:android:8ec76f930fc2175338d96d',
    messagingSenderId: '485836775960',
    projectId: 'altrupets-dev',
    storageBucket: 'altrupets-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvh4sYxl7gV1Ks_roqgl3moQORlrxcXgU',
    appId: '1:485836775960:ios:7c8499959ee2806438d96d',
    messagingSenderId: '485836775960',
    projectId: 'altrupets-dev',
    storageBucket: 'altrupets-dev.firebasestorage.app',
    iosBundleId: 'com.altrupets.altrupets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn1HhAGfV3EVX4rwvid6-FDKNafRa3xNU',
    appId: '1:485836775960:web:7bce06eada22237738d96d',
    messagingSenderId: '485836775960',
    projectId: 'altrupets-dev',
    authDomain: 'altrupets-dev.firebaseapp.com',
    storageBucket: 'altrupets-dev.firebasestorage.app',
    measurementId: 'G-SN9QK8XGNZ',
  );
}
