import { registerEnumType } from '@nestjs/graphql';

export enum NotificationType {
  RESCUE_ALERT = 'RESCUE_ALERT',
  RESCUE_ACCEPTED = 'RESCUE_ACCEPTED',
  RESCUE_TRANSFERRED = 'RESCUE_TRANSFERRED',
  SUBSIDY_CREATED = 'SUBSIDY_CREATED',
  SUBSIDY_APPROVED = 'SUBSIDY_APPROVED',
  SUBSIDY_REJECTED = 'SUBSIDY_REJECTED',
  SUBSIDY_VET_ASSIGNED = 'SUBSIDY_VET_ASSIGNED',
  ABUSE_REPORT_UPDATE = 'ABUSE_REPORT_UPDATE',
  ABUSE_REPORT_FILED = 'ABUSE_REPORT_FILED',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  ADOPTION_APPLICATION_SUBMITTED = 'ADOPTION_APPLICATION_SUBMITTED',
  ADOPTION_VISIT_SCHEDULED = 'ADOPTION_VISIT_SCHEDULED',
  ADOPTION_APPROVED = 'ADOPTION_APPROVED',
  ADOPTION_REJECTED = 'ADOPTION_REJECTED',
}

registerEnumType(NotificationType, { name: 'NotificationType' });
