# InfisicalSecret CRDs for AltruPets
# These resources sync secrets from Infisical to Kubernetes

# Backend credentials - contains all secrets for the dev environment
# Used by: PostgreSQL, Backend API, Web apps
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-backend-secret
  namespace: altrupets-dev
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: altrupets-monorepo
        envSlug: dev
        secretsPath: /
      credentialsRef:
        secretName: infisical-operator-credentials
        secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: backend-secret
      secretNamespace: altrupets-dev
      creationPolicy: Orphan
