# InfisicalSecret CRDs for AltruPets
# These resources sync secrets from Infisical to Kubernetes

# PostgreSQL credentials (synced to default namespace)
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-postgres-secret
  namespace: default
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-operator-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        envSlug: dev
        secretsPath: /
  managedSecretReference:
    secretName: postgres-dev-secret
    secretNamespace: default
    creationPolicy: Orphan
---
# Backend credentials (synced to altrupets-dev namespace)
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-backend-secret
  namespace: altrupets-dev
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-operator-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        envSlug: dev
        secretsPath: /
  managedSecretReference:
    secretName: backend-secret
    secretNamespace: altrupets-dev
    creationPolicy: Orphan
