/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-brand-primary)',
          0: 'var(--color-primary-0)',
          10: 'var(--color-primary-10)',
          20: 'var(--color-primary-20)',
          30: 'var(--color-primary-30)',
          40: 'var(--color-primary-40)',
          50: 'var(--color-primary-50)',
          60: 'var(--color-primary-60)',
          70: 'var(--color-primary-70)',
          80: 'var(--color-primary-80)',
          90: 'var(--color-primary-90)',
          95: 'var(--color-primary-95)',
          99: 'var(--color-primary-99)',
          100: 'var(--color-primary-100)',
        },
        secondary: {
          DEFAULT: 'var(--color-brand-secondary)',
          0: 'var(--color-secondary-0)',
          10: 'var(--color-secondary-10)',
          20: 'var(--color-secondary-20)',
          30: 'var(--color-secondary-30)',
          40: 'var(--color-secondary-40)',
          50: 'var(--color-secondary-50)',
          60: 'var(--color-secondary-60)',
          70: 'var(--color-secondary-70)',
          80: 'var(--color-secondary-80)',
          90: 'var(--color-secondary-90)',
          95: 'var(--color-secondary-95)',
          99: 'var(--color-secondary-99)',
          100: 'var(--color-secondary-100)',
        },
        accent: {
          DEFAULT: 'var(--color-brand-accent)',
          0: 'var(--color-accent-0)',
          10: 'var(--color-accent-10)',
          20: 'var(--color-accent-20)',
          30: 'var(--color-accent-30)',
          40: 'var(--color-accent-40)',
          50: 'var(--color-accent-50)',
          60: 'var(--color-accent-60)',
          70: 'var(--color-accent-70)',
          80: 'var(--color-accent-80)',
          90: 'var(--color-accent-90)',
          95: 'var(--color-accent-95)',
          99: 'var(--color-accent-99)',
          100: 'var(--color-accent-100)',
        },
        warning: {
          DEFAULT: 'var(--color-brand-warning)',
          0: 'var(--color-warning-0)',
          10: 'var(--color-warning-10)',
          20: 'var(--color-warning-20)',
          30: 'var(--color-warning-30)',
          40: 'var(--color-warning-40)',
          50: 'var(--color-warning-50)',
          60: 'var(--color-warning-60)',
          70: 'var(--color-warning-70)',
          80: 'var(--color-warning-80)',
          90: 'var(--color-warning-90)',
          95: 'var(--color-warning-95)',
          99: 'var(--color-warning-99)',
          100: 'var(--color-warning-100)',
        },
        error: {
          DEFAULT: 'var(--color-brand-error)',
          0: 'var(--color-error-0)',
          10: 'var(--color-error-10)',
          20: 'var(--color-error-20)',
          30: 'var(--color-error-30)',
          40: 'var(--color-error-40)',
          50: 'var(--color-error-50)',
          60: 'var(--color-error-60)',
          70: 'var(--color-error-70)',
          80: 'var(--color-error-80)',
          90: 'var(--color-error-90)',
          95: 'var(--color-error-95)',
          99: 'var(--color-error-99)',
          100: 'var(--color-error-100)',
        },
        success: {
          DEFAULT: 'var(--color-brand-success)',
          0: 'var(--color-success-0)',
          10: 'var(--color-success-10)',
          20: 'var(--color-success-20)',
          30: 'var(--color-success-30)',
          40: 'var(--color-success-40)',
          50: 'var(--color-success-50)',
          60: 'var(--color-success-60)',
          70: 'var(--color-success-70)',
          80: 'var(--color-success-80)',
          90: 'var(--color-success-90)',
          95: 'var(--color-success-95)',
          99: 'var(--color-success-99)',
          100: 'var(--color-success-100)',
        },
        neutral: {
          DEFAULT: 'var(--color-neutral-50)',
          0: 'var(--color-neutral-0)',
          10: 'var(--color-neutral-10)',
          20: 'var(--color-neutral-20)',
          30: 'var(--color-neutral-30)',
          40: 'var(--color-neutral-40)',
          50: 'var(--color-neutral-50)',
          60: 'var(--color-neutral-60)',
          70: 'var(--color-neutral-70)',
          80: 'var(--color-neutral-80)',
          90: 'var(--color-neutral-90)',
          95: 'var(--color-neutral-95)',
          99: 'var(--color-neutral-99)',
          100: 'var(--color-neutral-100)',
        },
        surface: {
          DEFAULT: 'var(--color-neutral-99)',
          bright: 'var(--color-neutral-100)',
        },
        'on-surface': 'var(--color-neutral-10)',
        outline: {
          DEFAULT: 'var(--color-neutral-70)',
          variant: 'var(--color-neutral-80)',
        },
      },
      fontFamily: {
        primary: 'var(--font-family-primary)',
        header: 'var(--font-family-header)',
        tertiary: 'var(--font-family-tertiary)',
      },
      transitionDuration: {
        short: '150ms',
        medium: '200ms',
        long: '300ms',
      },
    },
  },
  plugins: [],
}
